PreCommit:
  RuboCop:
    enabled: true
    on_warn: pass
    problem_on_unmodified_line: warn
    command: ['bundle', 'exec', 'rubocop']

verify_signatures: false

PostCheckout:
  CustomScript:
    enabled: true
    required_executable: '.check_migration_script.sh'
