PreCommit:
  RuboCop:
    enabled: true
    on_warn: pass
    problem_on_unmodified_line: warn
    command: ['bundle', 'exec', 'rubocop']
#  CustomScript:
#    enabled: true
#    command: ['sh', 'check_migration_script.sh']

verify_signatures: false
