name: Echo changed files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  echo:
    runs-on: ubuntu-latest
    name: Echo Changed Files
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29

      - name: Check Timstamps
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          ${{ steps.changed-files.outputs.all_changed_files }} | grep 'db/data\|migrate' | xargs basename -a |  xargs sh check_timestamp.sh
