name: Check migrations age

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed migrations files
        id: changed-files
        uses: tj-actions/changed-files@v29
        with:
          files: |
            db/data/**
            db/migrate/**

      - name: List all changed files
        run: |
          sh check_migration_script ${{ steps.changed-files.outputs.all_changed_files }}